name: Check Osiris versus latest penumbra
on: 
  schedule:
    - cron: "15 18 * * *"

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout osiris
        uses: actions/checkout@v2
        with:
          path: osiris

      - name: Check out penumbra repo
        uses: actions/checkout@v2
        with:
          repository: penumbra-zone/penumbra
          path: penumbra
          lfs: true

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            osiris
            penumbra

      - name: cargo fmt
        run:
          cargo fmt --all -- --check
        working-directory: osiris
